
services:
  # Serviço 1: O nosso Banco de Dados
  db:
    image: postgres:15-alpine
    container_name: devops-postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api_network

  # Serviço 2: A nossa API Python
  web-api:
    build: .
    container_name: devops-python-api
    restart: always
    ports:
      - "3000:8000"
    environment:
      - APP_ENV=production
      - API_SECRET_KEY=${API_SECRET_KEY}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      - db
    networks:
      - api_network

# Redes para isolar a comunicação entre os containers
networks:
  api_network:
    driver: bridge

# Volumes para garantir que os dados do banco não sumam quando o container desligar
volumes:
  postgres_data: