name: Pipeline de Integração Contínua (CI)

# 1. Gatilho: O que faz a esteira rodar?
on:
  push:
    branches: [ "main" ] # Roda toda vez que houver um git push na branch main
  pull_request:
    branches: [ "main" ] # Roda se alguém tentar abrir um pull request para a main

# 2. Os trabalhos (jobs) que a esteira vai executar
jobs:
  build-and-test:
    # Diz ao GitHub para usar uma máquina virtual Linux (Ubuntu) atualizada
    runs-on: ubuntu-latest

    steps:
    # ==========================================
    # PASSOS DE APLICAÇÃO E DOCKER
    # ==========================================
    # Passo 1: Copia o código do seu repositório para dentro da máquina virtual
    - name: Baixar o código do repositório
      uses: actions/checkout@v5

    # Passo 2: Configura o ambiente Python na máquina virtual
    - name: Configurar o Python 3.11
      uses: actions/setup-python@v6
      with:
        python-version: "3.11"

    # Passo 3: Instala as dependências para simular o ambiente e checar erros de sintaxe
    - name: Instalar dependências locais
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Passo 4: Validar o build da imagem Docker
    - name: Testar a construção da Imagem Docker
      run: |
        docker build -t minha-api-test-ci:${{ github.sha }} .

    # ==========================================
    # PASSOS DE VALIDAÇÃO DO TERRAFORM
    # ==========================================

    # Passo 6: Instala o Terraform na máquina virtual
    - name: Configurar o Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.5.7"
    
    # Passo 7: Validar a Formatação do Terraform
    - name: Validar a formatação do Terraform
      run: terraform fmt -check -recursive
      working-directory: ./terraform
    
    # Passo 8: Inicializar o Terraform
    - name: Inicializar o Terraform no Runner
      run: terraform init
      working-directory: ./terraform

    # Passo 9: Validar a Sintaxe e Configuração do Terraform
    - name: Validar a sintaxe e Lógica do Terraform
      env:
        TF_VAR_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAACIfakekeyforvalidate"
      run: terraform validate
      working-directory: ./terraform

    # Mensagem de sucesso nos logs
    - name: Feedback de conclusão
      run: echo "Parabéns! Docker e Terraform foram validados com sucesso no pipeline."